### ISSUE TITLE
Windows standalone binary

### ISSUE THREAD

**Issue by sergeevabc** [riyadhalnur/quote-cli#21]
Dear Riyadh,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows w/o Node?
I’m told that either [Nexe][1] or [EnclosureJS][2] might help you to achieve that.

[1]: https://www.npmjs.com/package/nexe
[2]: http://enclosejs.com/

**Comment by riyadhalnur** [comment]
While the solution is easy using existing tools, it's not something I think I want to spend my time on because I don't a demand for it. For individual needs, you can easily build an executable using the tools you mentioned for use on your machine.

**Comment by sergeevabc** [comment]
Current state of Quote requires Node to be installed on host machine which is a dependency itself.
Other CLI gems like [sysinternals][1], [ffmpeg][2], [jdupes][3], [wget][4], [pandoc][5], [sift][6] could be run simply from USB stick.

[1]: https://live.sysinternals.com/
[2]: http://www.videohelp.com/software/ffmpeg
[3]: https://github.com/jbruchon/jdupes/
[4]: https://eternallybored.org/misc/wget/
[5]: https://github.com/jgm/pandoc
[6]: https://github.com/svent/sift/

**Comment by riyadhalnur** [comment]
Yes, NodeJS is a dependency. This is purely a NodeJS terminal application.
